export const BEATMAKING_I_EMBED =
  '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1348954282&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/zenr0" title="renzo" target="_blank" style="color: #cccccc; text-decoration: none;">renzo</a> · <a href="https://soundcloud.com/zenr0/sets/beatmaking-i" title="BEATMAKING I" target="_blank" style="color: #cccccc; text-decoration: none;">BEATMAKING I</a></div>';

export const BEATMAKING_II_EMBED =
  '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1409295232&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/zenr0" title="renzo" target="_blank" style="color: #cccccc; text-decoration: none;">renzo</a> · <a href="https://soundcloud.com/zenr0/sets/beatmaking-ii" title="BEATMAKING II" target="_blank" style="color: #cccccc; text-decoration: none;">BEATMAKING II</a></div>';

export const ELECTROACOUSTIC_EMBED =
  '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1442845540&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/zenr0" title="renzo" target="_blank" style="color: #cccccc; text-decoration: none;">renzo</a> · <a href="https://soundcloud.com/zenr0/sets/electroacoustic" title="Electroacoustic" target="_blank" style="color: #cccccc; text-decoration: none;">Electroacoustic</a></div>';

export const EVERYDAY_EMBED =
  '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1299511324&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/zenr0" title="renzo" target="_blank" style="color: #cccccc; text-decoration: none;">renzo</a> · <a href="https://soundcloud.com/zenr0/sets/everyday" title="everyday" target="_blank" style="color: #cccccc; text-decoration: none;">everyday</a></div>';

export const DRAFTS =
  '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1298868898&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/zenr0" title="renzo" target="_blank" style="color: #cccccc; text-decoration: none;">renzo</a> · <a href="https://soundcloud.com/zenr0/sets/drafts" title="drafts" target="_blank" style="color: #cccccc; text-decoration: none;">drafts</a></div>';

export const MTC =
  '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/1298895805&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/zenr0" title="renzo" target="_blank" style="color: #cccccc; text-decoration: none;">renzo</a> · <a href="https://soundcloud.com/zenr0/sets/2017-to-2019" title="2017-2019" target="_blank" style="color: #cccccc; text-decoration: none;">2017-2019</a></div>';

export const EMBEDS = [
  BEATMAKING_I_EMBED,
  BEATMAKING_II_EMBED,
  ELECTROACOUSTIC_EMBED,
  EVERYDAY_EMBED,
  DRAFTS,
  MTC,
];
